#!/bin/bash

workspace_id=$(hyprctl activeworkspace -j | jq -r '.id')

if [ $workspace_id == 1 ]; then
	echo "「　思想を閉ざす事勿れ\n変化を恐るる事勿れ　」"
elif [ $workspace_id == 2 ]; then
	echo "「　望む真に非ず\n真実を常求めよ　」"
elif [ $workspace_id == 3 ]; then
	echo "「　科学をもって\n自然の理を理解せよ　」"
elif [ $workspace_id == 4 ]; then
	echo "「　各々は　己が肉体を制する権利を持つものなり　」"
elif [ $workspace_id == 5 ]; then
	echo "「　善に神必要非ず　」"
elif [ $workspace_id == 6 ]; then
	echo "「　自業あれば　自得あり　」"
elif [ $workspace_id == 7 ]; then
	echo "「　己が欲するよう他を接せよ\n他の視点を尊重せよ　」"
elif [ $workspace_id == 8 ]; then
	echo "「　他人と　来たるべき未来を考慮せよ　」"
elif [ $workspace_id == 9 ]; then
	echo "「　人生一本道に非ず　」"
elif [ $workspace_id == 10 ]; then
	echo "「　去れば花園を築くべし　」"
fi
